package com.parata.constants;

public enum CONTEXT {
    POSITION1, POSITION2,
    USER_ID_TO_HARD_DELETE, USER_EMAIL_TO_HARD_DELETE,USER_MODEL_TO_HARD_DELETE,
    ORGANIZATION_ID_TO_HARD_DELETE, FIRSTEMAILCOUNT,LASTEMAILCOUNT,
    NEW_USER_USERNAME, NEW_USER_PASSWORD,AUTHORIZATION_TOKEN,AUTHORIZATION_PM_TOKEN,RESPONSE_TEXT,RESPONSE_CODE,RESPONSE_BODY,
    OVERALLUPTIME,OVERALLUTTIME,OVERALLIDLETIME,OVERALLTRAYLOAD,OVERALLCANISTERLOAD,OVERALLMECHANICAL,OVERALLOPERATORIN,OVERALLDOWNTIME,
    DEVICEID,CANISTERRATIO,TRAYRATIO,TRAYRATIO1,TRAYRATIO2,CUSTOMERID;
    }



